### ISSUE TITLE
Dependencies for running --medaka argument

### ISSUE THREAD

**Issue by Alxdu** [ksahlin/isONclust#14]
Running the --medaka argument in the isONclust environment will result in error. 

Do we need to install medaka in the same environment with isONclust? Will it break any of the other dependecies? 

Thank you

UPDATE: I went ahead and installed medaka in the same environment with isONclust. 
Running the --medaka argument returns the following error (which is the same error when medaka was not manually installed )
`Traceback (most recent call last):
  File "/home/axd/miniconda3/envs/isonclust/bin/isONclust", line 263, in <module>
    main(args)
  File "/home/axd/miniconda3/envs/isonclust/bin/isONclust", line 139, in main
    print("Saving references in:", f.name)
UnboundLocalError: local variable 'f' referenced before assignment`

**Comment by ksahlin** [comment]
Hi @Alxdu,

Ah, medaka was never integrated into `isONclust`. The line before the one you pasted will read `Currently not implemented` The parameter should have never be introduced in the released version. Sorry, for the oversight. 

Two options: 1. Either run the consensus mode without medaka, or 2. Head over to https://github.com/ksahlin/NGSpeciesID and use `NGSpeciesID`. `NGSpeciesID` is essentially `isONclust`+ `consensus`  and some more features. It's an adapted version for clustering and consensus of amplicon data. I think it's safe to even install it in the same conda environment as `isONclust`.


The `--consensus` mode in `isONclust` was a draft implementation for `NGSpeciesID` but I decided to move this implementation to a different repo as it is designed for other types of data (e.g., amplicon data). Note that the `--consensus` mode should not be used on isoforms as it will produce consensus from each cluster, thus can merge reads from different transcripts.

**Comment by Alxdu** [comment]
@ksahlin I genuinely appreciate your feedback. 

You are correct, I have been testing isONclust with amplicon data (single or mixed amplicon pools) and found it very interesting, especially with SPOA integration for consensus on clusters. And I was then running medaka polish in a follow-up step. 

I think it did a great job on single/"pure" amplicons where clustering would effectively function as a noise reduction step, or as a quick way to detect contaminant DNA in samples. I was then curious to see if it can distinguish mixed amplicons (16S or rrn) from closely related species and generate consensus for each species. I also wondered if it could work to obtain quality consensus from more complex (i.e., metagenomic) datasets; e.g., when subsampling within a particular taxon clade.

I will try NGSpeciesID, thank you for pointing me that way. Great tools. Thank you for sharing them publicly.
