### ISSUE TITLE
get_sorted_fastq_for_cluster.py, line 124  //  p_no_error_in_kmers = 1.0 - exp_errors_in_kmers/ float((len(seq) - k +1))

### ISSUE THREAD

**Issue by uqvirg** [ksahlin/isONclust#3]
Hi,
I've run isONclust with the test: " isONclust --fastq test/sample_alz_2k.fastq --outfolder output ", it was ok.
After that 
I've tried to run isONclust on a sugarcane fastq file, read of insert of 301 020 reads. 
isONclust --fastq reads_of_insert.fastq --outfolder output1

and I had the error: " p_no_error_in_kmers = 1.0 - exp_errors_in_kmers/ float((len(seq) - k +1))
ZeroDivisionError: float division by zero".

Do you know what could be the problem ? 
Thank you,
Virgg

------------------------  Full LOG  ----------------------------
isONclust --fastq /30days/uqvperlo/smrtanalysis/output/merge_data/reads_of_insert.fastq --outfolder output1
started sorting seqs
0 reads processed.
10000 reads processed.
20000 reads processed.
30000 reads processed.
40000 reads processed.
50000 reads processed.
60000 reads processed.
70000 reads processed.
80000 reads processed.
90000 reads processed.
Traceback (most recent call last):
  File "/home/uqvperlo/.conda/envs/isonclust/bin/isONclust", line 178, in <module>
    main(args)
  File "/home/uqvperlo/.conda/envs/isonclust/bin/isONclust", line 67, in main
    sorted_reads_fastq_file = get_sorted_fastq_for_cluster.main(args)
  File "/home/uqvperlo/.conda/envs/isonclust/lib/python3.7/site-packages/modules/get_sorted_fastq_for_cluster.py", line 124, in main
    p_no_error_in_kmers = 1.0 - exp_errors_in_kmers/ float((len(seq) - k +1))
ZeroDivisionError: float division by zero

**Comment by uqvirg** [comment]
Thank you,
It works well (I have currently more that twice isoform than with IsoCon, I'm working on it).
Do you have an easy way to transform the "cluster_origins.csv" to a fasta file ?
Thank you again,
Virgg

**Comment by ksahlin** [comment]
Glad you find it useful! Unsure how you want to use isONclust but it only clusters the reads for you. No error correction is performed to remove reads from the same transcript. Maybe you have a downstream step to take that into account.

Best,
K

**Comment by ksahlin** [comment]
This error should be fixed in [v0.0.4](https://github.com/ksahlin/isONclust/releases/tag/0.0.4).
