### ISSUE TITLE
Incorporation of isONclust to a currently used pipeline (Iso-Seq, PacBio)

### ISSUE THREAD

**Issue by emaleckova** [ksahlin/isONclust#5]
Hello everyone,
I just finished processing my Iso-Seq data and the pipeline I used, in brief, consisted of the isoseq3 steps, CD-HIT-EST followed by Cogent (using the CD-HIT outcome for this step) and Cupcake to collapse isoforms (as described in the [tutorial](https://github.com/Magdoll/Cogent/wiki/Tutorial:-Using-Cogent-to-collapse-redundant-transcripts-in-absence-of-genome)). Now, my goal is to include isONclust to the pipeline and I have few questions regarding the steps I should take:

1. Most importantly, my data originate from four flow cells. Should I merge the four FLNC sets and perform isONclust on this data or do the clustering independently for each flow cell? I did not prepare the libraries myself but from my understanding, some size selection was employed in the process, meaning I would expect at least a portion of transcripts being uique to a certain flow cell.

2. In my first try, after` isoseq3 cluster `step, I performed polishing with all the initial subreads (`isoseq3 polish`). Is it still OK to keep this step once isONclust was run?

3. By using isONclust, can I omit the CD-HIT step now? I am not a bioinformatician by training and still new in the field, so I may be wrong. My understanding, however, was that CD-HIT takes the longest representative sequence in each cluster, without building any kind of consensus, considering quality scores etc, and that is why I want to implement isONclust now, hoping I can then proceed with the Cogent/Cupcake steps directly. Does it make sense to proceed like that?

I am not sure whether it is relevant, but I will be doing transcript collapsing without a reference genome.

Thank you very much for taking the time to address my concerns and questions.

Best,
Eva

**Comment by ksahlin** [comment]
Hi Eva, 


1. It depends on your "collapsing"-goal. If you want to have as much coverage as possible for each transcript/gene/gene family, I suggest merging the flow-cells.  I guess you can always separate the reads back to the flowcell they originated from based on the accessions of the reads (if you are interested in some differences between the flowcells, e.g. if you barcoded different tissues or similar).  

2. Do you mean to run isoseq3 cluster/polish before running isONclust? Yes, I assume that's fine. However, isONclust has only been designed and evaluated for clustering of the original flnc reads. 

3. I'm assuming cogent/cupcake will do a better job than CD-HIT, as it is designed for this type of data (I have not evaluated this, however). So based only on intuition, I would recommend running Isonclust then cogent. 

Best,
Kristoffer

**Comment by emaleckova** [comment]
Hi Kristoffer,

Thank you for your quick response. I am much more confident now.

If possible, I would like to ask for further reassurance to my second point. I plan to use polished CCS sequences to produce FLNCs. At that point, I am ready to switch to your tool, which basically replaces the `isoseq3 cluster `step. Do I understand it right? And since `isonclust `takes the quality scores into account and I polished CCS before, there should be no need for further polishing with `isoseq3 polish`, do I get it right?

Thanks again.

Best,
Eva

**Comment by ksahlin** [comment]
Seems like a promising approach. Yes, I think in your particular setting, `isONclust` would replace `isoseq3 cluster`.  So if I understand you correctly, you would run the following pipeline: 
1. `ccs` 2. `lima` 3. `isONclust` 4. `Cogent`

It is correct that `isONclust` takes variable CCS read quality into account. However, I want to reiterate that isONclust only groups the CCS reads together based on gene(families). It does not do further polishing/error correction. It is possible that maybe cogent can be used for the "raw" clusters generated by `isONclust`. Note however that cogent is a bit sensitive to the size of the clusters (doesn't scale well to very large clusters). At least when I tried about a year ago --  maybe it has been updated.

**Comment by emaleckova** [comment]
Hello Kristoffer,

I have to admit I have been struggling quite a bit since we started the discussion here. I managed to obtain FLNC sequences and after merging my four subsets (originating from four flow cells), I obtained isONclust-based clusters. There were about 52 000 of them, and 49 % being singletons. Is such a high proportion of singleton clusters usual? _(On a side note since I was trying to do some kind of comparison: `isoseq3 cluster` actually generates three times as many singletons as HQ clusters...)_

For `Cogent`, I planned to use a kind of "representative" sequence for each of the detected clusters. For singletons, this is obviously easy. For multimember clusters, I thought of either taking the longest sequence in each cluster (something CD-HIT-EST does in my understanding) or trying to build a consensus sequence for each cluster. I had a look at alignments for randomly selected clusters of various sizes (e.g. five transcripts in there or few tens) and I found great variability in length as well as numerous gaps in those alignments. I assume all that these are biological, such as splice variants, as well as some sequencing errors still in there.

With the clusters available, how should I proceed to get a "correct" transcript representation as input for `Cogent`? I am worried that by making a wrong decision here, I will end up with a "fake genome", which would not "accurate" enough to "correctly" map the complete set of transcripts.

This also brings me to another point. The input for [Cogent-based isoform collapsing](https://github.com/Magdoll/Cogent/wiki/Tutorial:-Using-Cogent-to-collapse-redundant-transcripts-in-absence-of-genome) is expected to by HQ isoform sequences. In the scenario of generating clusters with `isONclust` (instead of `isoseq3 cluster`), should I still generate isoseq3-based clusters to be used at that or should I use FLNC sequences? I was thinking of FLNCs since, in the end, they were the initial input for either clustering algorithm. Is my thinking right?

Thank you very very much for your assistance.

Best,
Eva

**Comment by ksahlin** [comment]
Hi Eva,

Since `isONclust` cluster reads on _gene level_, `isoseq3 cluster` clusters reads on _transcript level_, it  is expected that `isoseq3 cluster` has more singletons than  `isONclust` since clustering on transcript vs gene level. It is expected  that some reads that doesn't fit anywhere (e.g., low quality/sequencing artifacts, pre-mRNA). While the proportion of _singletons clusters_ might look frighteningly high (49%),  it is probably a very low percentage of the total number of reads?

Yes it is expected that reads from the same gene (i.e., the same isONcorrect clusters) have gaps both from sequencing errors and exon differences. Why can't the reads from each `isONcorrect` cluster be processed by cogent to generate a consensus? I was under the assumption that this was the strategy. If not, `CD-HIT-EST`  seems reasonable (I'm not an expert on this tool).  I would otherwise suggest trying [spoa](https://github.com/rvaser/spoa) to reconstruct a single representative per cluster, however, it can miss exons that are very lowly abundant. You can also try [IsoCon](https://github.com/ksahlin/IsoCon) on each cluster separately (I'm the developer of the tool) for this.

For small clusters, you believe should use the original flnc sequences for this. However, for very large clusters (say >5,000 reads), cogent will not scale (unless there has been an update ot the algorithm). It is then good to run e.g., IsoCon for those clusters and use the final predicted transcripts.
