### ISSUE TITLE
isONclust: error: too few arguments

### ISSUE THREAD

**Issue by emaleckova** [ksahlin/isONclust#6]
Hello Kristoffer,

I have been having  (probably a trivial issue) with running `isonclust` and after two days of trying, I eventually would like to call for help.

I tried running `isonclust` on an Iso-Seq data using either flnc.fastq as an input or a combination of CCS and FLNC `.bam` files. In either case, the error was the same: "too few arguments". I thus downloaded the sample data set and ran `isONclust --isoseq --fastq sample_alz_2k.fastq --outfolder test` but the error was the same.

Subsequently, I tried specifying `--k` and `--w` instead of using `--isoseq` but the error was the same. Eventually, I tried with "my" data again and I specified every single parameter (using the default values). The command was thus: `isONclust --fastq Merged.FLNC.fastq --t 12 --isoseq --min_shared 5 --mapped_threshold 0.7 --aligned_threshold 0.4 --min_fraction 0.8 --min_prob_no_hits 0.1 --outfolder isONclust-191011` Nonetheless, there are still "too few arguments".

I assume it is some really small thing missing somewhere and if this is the case, I am sorry about it but I am stuck and out of ideas, what might be going on. Could you please help me? Many thanks.

Best,
Eva

**Comment by ksahlin** [comment]
Oh I think is a python v2 problem! (I should implement a check for this). Try running it with any version of python 3 and see if it works.

**Comment by ksahlin** [comment]
I verified that this error is isolated to python versions 2.x. isONclust is supported and tested on python version 3.4 and above. Installing `isONclust` from conda (as in `https://github.com/ksahlin/isONclust#INSTALLATION`) is the easiest option. Let me know if you run into other problems. Thanks!
